#define ENUMERATE_FILE_MODES \
    FILE_MODE(READONLY, 0)   \
    FILE_MODE(WRITEONLY, 1)  \
    FILE_MODE(READWRITE, 2)  \
    FILE_MODE(CREATE, 3)     \
    FILE_MODE(TRUNCATE, 4)   \
    FILE_MODE(APPEND, 5)

#define ENUMERATE_SEEK_MODES \
    SEEK_MODE(BEGINNING)     \
    SEEK_MODE(CURRENT)       \
    SEEK_MODE(END)
