#define ENUMERATE_FILE_MODES \
    FILE_MODE(READONLY)      \
    FILE_MODE(WRITEONLY)     \
    FILE_MODE(READWRITE)     \
    FILE_MODE(CREATE)        \
    FILE_MODE(TRUNCATE)      \
    FILE_MODE(APPEND)

#define ENUMERATE_SEEK_MODES \
    SEEK_MODE(BEGINNING)     \
    SEEK_MODE(CURRENT)       \
    SEEK_MODE(END)
