#define ENUMERATE_IO_MODES \
    IO_MODE(READONLY, 0)   \
    IO_MODE(WRITEONLY, 1)  \
    IO_MODE(READWRITE, 2)  \
    IO_MODE(CREATE, 3)     \
    IO_MODE(TRUNCATE, 4)   \
    IO_MODE(APPEND, 5)

#define ENUMERATE_SEEK_MODES \
    SEEK_MODE(BEGINNING)     \
    SEEK_MODE(CURRENT)       \
    SEEK_MODE(END)
