#pragma once

#define ENUMERATE_WM_COMMANDS  \
    WM_COMMAND(CREATE_WINDOW)  \
    WM_COMMAND(DESTROY_WINDOW) \
    WM_COMMAND(POP_EVENT)      \
    WM_COMMAND(SET_TITLE)      \
    WM_COMMAND(INVALIDATE_RECT)
